### ISSUE TITLE
Wallet Connect button doesn't work?

### ISSUE THREAD

**Issue by themsay** [cosmostation/cosmostation-android#100]
Hi,

I've tried to use Wallet Connect for the first time by clicking the button I'm getting ```Preparing...``` and nothing more, but all 3 app permissions granted.

Do anybody know the reason why WalletConnect doesn't work on my Samsung android version: 9 and Cosmostation: v1.5.45, or just a general issue with this app?

**Comment by Kwonhyukjoon** [comment]
Hi, this is not an issue - Wallet Connect function is still under development. We’re planning to release WC support soon.
