### ISSUE TITLE
"My Deposited Value"  balances are not updating correctly in the Kava network pool. 

### ISSUE THREAD

**Issue by Jgoodwin64** [cosmostation/cosmostation-android#121]
In the Cosmostation android app under "My Deposited Value"  in the Kava DeFi - Pool tab, the values of the new LP coins are not being reflected when calculating the total amount the user deposited. It reflects the amount of USDX deposited but not ATOM, OSMO, LUNA and so forth. It calculates correctly for native pairs though.  I am running v1.5.47 of the app. This issue applies to the "Total Deposited Value" as well.

**Comment by Kwonhyukjoon** [comment]
Thank you!
I'll fix it in the next version.
