### ISSUE TITLE
Out of gas error for Osmosis

### ISSUE THREAD

**Issue by mdmohsin7** [cosmostation/cosmostation-android#240]
While redelegating, I get the out of gas error for Osmosis if I don't press the "Check Estimate Gas Amount" button to simulate the transaction before actually proceeding with the transaction. This has been happening a lot lately for Osmosis.

I guess it would be better if `onSetFee` is also called on refresh for Osmosis too, just like it is being done for Evmos as of now in the  `onRefreshTab()` in `StepFeeSetFragment`. This would eliminate the hassle for an average user.

```
    else if (getSActivity().mBaseChain.equals(BaseChain.OSMOSIS_MAIN)) {
            onSetFee(mSelectedGasDenomPosition);
            onCheckTxType();
        }
```

**Comment by wannabit-yongjoo** [comment]
Thanks a lot good suggestion👍

**Comment by Kwonhyukjoon** [comment]
👍

**Comment by Kwonhyukjoon** [comment]
https://github.com/cosmostation/cosmostation-android/pull/244/files
