### ISSUE TITLE
Kava incentives ui bug.

### ISSUE THREAD

**Issue by Jgoodwin64** [cosmostation/cosmostation-android#436]
When a kava wallet is loaded  it shows the balance of the incentives  for liquid staking. If another tab is clicked on then clicked back to the main tab it has an incentive display error. I tested it out and got it to display that I had 100  Kava waiting to be claimed when I only had .05 I wouldn't say it is a big issue but it is annoying.

**Comment by wannabit-yongjoo** [comment]
I double checked this bug.
plz fix ASAP @Kwonhyukjoon

**Comment by kimheeje12** [comment]
@Jgoodwin64 The issue has been resolved and will be reflected in the next release. Thanks for the bug report!

**Comment by wannabit-yongjoo** [comment]
https://github.com/all-contributors please add @Jgoodwin64 for  bug
