### ISSUE TITLE
Potential bug in Kava 

### ISSUE THREAD

**Issue by Jgoodwin64** [cosmostation/cosmostation-android#454]
When connected to the Kava dapp in Cosmostation app there is a bug when casting a vote.  It says "error during broadcasting 
Signature verification failed please verify. account number " however voting on kava works normally from the wallet tab governance button 
I only get the error when connected to the dapp connected via wallet connect.

**Comment by Jgoodwin64** [comment]
![Screenshot_20221208-233751_Cosmostation](https://user-images.githubusercontent.com/94092417/206627839-8f95c835-7996-4d9f-95df-ad5686b17cf4.png)

**Comment by Kwonhyukjoon** [comment]
Thanks for the bug report! We will check.

**Comment by soaryong-c** [comment]
#490 will be release
