### ISSUE TITLE
Does cosmostation support wallet connect?

### ISSUE THREAD

**Issue by PhantomJoness** [cosmostation/cosmostation-android#456]
Hello,

I'm trying to connect wallet on cosmostation from my native android dapp using wallet connect. After calling Intent, wallet connect showing only few apps like metamask, trustwallet etc. Not showing cosmostation inside the app chooser. 
Is there any possibility to connect cosmostation wallet using deep linking(Wallet connect) from native android app? 

![Screenshot_2022-12-09-23-13-04-289_android](https://user-images.githubusercontent.com/95672491/206761873-28bce9ab-e0f4-4b36-81c5-a7221b8d5919.jpg)

**Comment by soaryong-c** [comment]
@PhantomJoness
What deep linking scheme can you share to display the select dialog?
If it is an open source project, please let me know what kind of project it is.

**Comment by PhantomJoness** [comment]
Hi @soaryong-c ,
I'm using [https://github.com/WalletConnect/WalletConnectKotlinV2](Wallet connect library). They have sample demo application [https://github.com/WalletConnect/WalletConnectKotlinV2/tree/develop/sign](url) for dapp and wallet.

**Comment by PhantomJoness** [comment]
Thanks @soaryong-c , it's working now. Can I use support chain feature in this build?

**Comment by soaryong-c** [comment]
@PhantomJoness 
Are you talking about adding a custom chain?

**Comment by Usernamethoma** [comment]
> Hello,
> 
> I'm trying to connect wallet on cosmostation from my native android dapp using wallet connect. After calling Intent, wallet connect showing only few apps like metamask, trustwallet etc. Not showing cosmostation inside the app chooser. 
> Is there any possibility to connect cosmostation wallet using deep linking(Wallet connect) from native android app? 
> 
> ![Screenshot_2022-12-09-23-13-04-289_android](https://user-images.githubusercontent.com/95672491/206761873-28bce9ab-e0f4-4b36-81c5-a7221b8d5919.jpg)
> 
> 
> 

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9
