### ISSUE TITLE
Support for testnet chains

### ISSUE THREAD

**Issue by luca992** [cosmostation/cosmostation-android#498]
Right now I am using cosmostation to test out using WalletConnect v2 with our dapp. Secret network mainnet `secret-4` works great. But, I would like to test out our dapp which is only deployed on testnet `pulsar-2` atm. 

Cosmostation just crashes when I request `cosmos:pulsar-2` with a walletconnect deeplink right now.

**Comment by soaryong-c** [comment]
currently, we don't support test chain.
can you share dev page?

**Comment by luca992** [comment]
Well it looks like you support one ![testnet](https://user-images.githubusercontent.com/4157455/214651185-890de442-d493-45a1-95bd-4d52f32bc6ec.png)

I'm working on eqoty.io and we're still only on testnet
