### ISSUE TITLE
Why raw_log  is empty in the response of any transaction

### ISSUE THREAD

**Issue by PhantomJones** [cosmostation/cosmostation-android#50]
Following is the response after broadcast:

{"memoizedIsInitialized":1,"txResponse_":{"code_":0,"codespace_":"","data_":"","gasUsed_":0,"gasWanted_":0,"height_":0,"info_":"","logs_":[],"memoizedIsInitialized":-1,"rawLog_":"[]","timestamp_":"","txhash_":"4BEB089FF4DD0F6282605BCF2A7F6F472578FBD39B36F47D4A597B5D0463A00","unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0},"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0}

**Comment by Papan96** [comment]
In web,  it looks fine and response structure is different also(used cosmos-sdk). Can anyone explain what to do for getting all useful data in the response in android?

**Comment by wannabit-yongjoo** [comment]
async mode broadcast gives only txhash with cosmos sdk

**Comment by wannabit-yongjoo** [comment]
sync mode gives all data when tx writed blockchain
but need some more waiting time
