### ISSUE TITLE
Starname domains doesn't resolve

### ISSUE THREAD

**Issue by xpt1x** [cosmostation/cosmostation-android#551]
Starnames with pattern: `name*domain` work at time of starname resolution but starnames with pattern: `*domain` doesn't work
It shows `Unregistered name service` error
```xml
    <string name="error_invalid_icns">Unregistered NameService.</string>
```

**Comment by Kwonhyukjoon** [comment]
Thank you!
I'll check it

**Comment by wannabit-yongjoo** [comment]
https://github.com/cosmostation/cosmostation-ios/commit/a6c6f75e302f6ebc674bcf22f2b6b2ca33b9ee63
IOS side bug fixed
Thanks a lot @xpt1x

**Comment by wannabit-yongjoo** [comment]
![Simulator Screen Shot - iPhone 14 Pro - 2023-03-31 at 19 49 13](https://user-images.githubusercontent.com/38899600/229100631-54fd74ce-b2fa-4000-b27d-9d14f5df5096.png)

**Comment by xpt1x** [comment]
Thanks @wannabit-yongjoo for taking time to resolve this
However with your reference commit i found some incorrect validations, please fix them as well.
I raised the issue on ios repo: https://github.com/cosmostation/cosmostation-ios/issues/294
