### ISSUE TITLE
How can I run this project on my computer?

### ISSUE THREAD

**Issue by vladut-lp** [cosmostation/cosmostation-android#59]
After checking out the project locally (master branch), I tried running the project. I receive this error on build: 

`FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  path\app\src\nullnull\debug\google-services.json
  path\app\src\debug\nullnull\google-services.json
  path\app\src\nullnull\google-services.json
  path\app\src\debug\google-services.json
  path\app\src\nullnullDebug\google-services.json
  path\app\google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:validateSigningDebug'.
> Keystore file 'path\app\debug.keystore' not found for signing config 'debug'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org
`

Can you help me? I have read the Readme but did not find any information about this.

Thanks!

**Comment by wannabit-yongjoo** [comment]
yes, to local build you need google-services.json
but this files is not shared in github cuz security.

1. you can build with your owen service files
2. remove firebase relation in gradle, apply plugins

**Comment by alvarogharo** [comment]
Solved the google services part, but what should I do with the `debug.keystore` file error.
