### ISSUE TITLE
Kava fee bug

### ISSUE THREAD

**Issue by Jgoodwin64** [cosmostation/cosmostation-android#613]
On latest android. 
When removing liquidity from Kava earn, I get a fee bug.  I am attempting to remove the max amount of liquidity I can by using the Max button.  
I currently have 0.9 Kava in the wallet, so it should work.

I tried again with slightly less than the max and it worked, but now I still have some in the pool.

![kava](https://github.com/cosmostation/cosmostation-android/assets/94092417/94e528cf-9f46-4c4f-8526-b77d52dc3693)

**Comment by Kwonhyukjoon** [comment]
Thanks for letting me know, I'll check.

**Comment by Kwonhyukjoon** [comment]
If you still experience the same situation, then kindly send us an email to support@cosmostation.io
