### ISSUE TITLE
Issue with new version importing medibloc wallet

### ISSUE THREAD

**Issue by cosmane** [cosmostation/cosmostation-android#632]
Something is wrong with the latest wallet. It updated on android, but it did not import the correct wallet address for Medibloc.
Previous address for Medibloc wallet is different from the one that's now on there and the coin count is 0.
When I check the prior address on the explorer the coins are still there on the prior address. There is no option on the Medibloc wallet to import the prior address.

The other wallets I notice have the prior address, such as Comos and Akash. Only Medibloc.

**Comment by cosmane** [comment]
I tried uninstalling the comstation wallet and reinstalling and reimporting using seed phrase. Same result.

**Comment by jeongeunlee1209** [comment]
Hello, sorry for the inconvenience after the Cosmostation mobile upgrade. It seems like your Medibloc wallet was saved in different HD Derivation Path. Please do not delete the app and please kindly send us an email to support@cosmostation.io, then our representative will kindly assist you on how to locate the wallet. Thank you and looking forward to receiving the email.
