### ISSUE TITLE
My data isnt transfering over

### ISSUE THREAD

**Issue by Cojr97** [cosmostation/cosmostation-android#641]
My data isnt transferring over to my wallet after i recovered it

**Comment by jp75300** [comment]
как быть есть решение?

**Comment by jp75300** [comment]
я все привязал через keprl

**Comment by Cojr97** [comment]
I speak english i dont know what that says im sorry

**Comment by jp75300** [comment]
I linked everything via keprl

**Comment by jp75300** [comment]
withdrawal of funds and exchange in osmosis is convenient

**Comment by jp75300** [comment]
You did it?

**Comment by jp75300** [comment]
we start within an hour, has your data been updated?

**Comment by Cojr97** [comment]
No it hasnt i recovered my wallet and nothing still

**Comment by jp75300** [comment]
do you do this through the wallet browser?

**Comment by Cojr97** [comment]
Im going to try it right now

**Comment by jp75300** [comment]
Did you succeed?

**Comment by Kwonhyukjoon** [comment]
Hello, sorry for the inconvenience after the Cosmostation mobile upgrade.Please do not delete the app and please kindly send us an email to support@cosmostation.io, then our representative will kindly assist you. Thank you and looking forward to receiving the email.

**Comment by Cojr97** [comment]
I have been trying all day todapy to get my data into my wallet pand
nothing is showing up

**Comment by Kwonhyukjoon** [comment]
If you send me the details via email, we will guide you.

**Comment by Cojr97** [comment]
What do i need to send

**Comment by jp75300** [comment]
what data are you not transferring?

**Comment by Cojr97** [comment]
All my assets arent showing in my wallet

**Comment by jp75300** [comment]
we tried the token through hell

**Comment by Cojr97** [comment]
Do you knoe how i will be able to get my assets back

**Comment by jeongeunlee1209** [comment]
Hello, could you please send us an email to support@cosmostation.io with the details such as the screenshot of the Cosmostation wallet and the wallet address that you are currently using? If you provide us with those data, then our representative will kindly assist you with the situation.

**Comment by jp75300** [comment]
What is the response time from support?

**Comment by jeongeunlee1209** [comment]
The response time from the Support Team should be fairly quick. However, we may request some more information if the details that the user provides are not sufficient enough for us to take a look into the situation. Please kindly send us an email to support@cosmostation.io with the details such as the screenshot and the wallet address that you are currently using so that our representative is able to assist you with the situation that you are experiencing.

**Comment by jp75300** [comment]
you need to speed up, or give me another wallet. We can't put it off. It is necessary to do everything today. There is another option to send your commission to another wallet manually

**Comment by jeongeunlee1209** [comment]
You should have received a reply from the email (support@cosmostation.io) on the types of data that you need to provide it to us. Please kindly send us the data so that our team is able to take a look into it. Thank you

**Comment by Cojr97** [comment]
Im sending it over right now

**Comment by Cojr97** [comment]
??
