### ISSUE TITLE
Resolve chain specific address from a starname

### ISSUE THREAD

**Issue by xpt1x** [cosmostation/cosmostation-android#68]
Right now on current version, using a starname for recipient only resolves IOV ( Starname specific ) address properly and fails to resolve for other chains, which was working before.

Currently it errors out with a message: "_Valid starname, but no matching address with this chain_", where the starname actually is having a valid matching address specific to chain under `asset:{denom}`

It should be fixed taking asset resource denom map into consideration from `resources` after resolving a starname

Other applicable project https://github.com/cosmostation/cosmostation-ios

Ref:
[Asset Ticker list - Starname Documentation](https://docs.starname.me/for-developers/tutorial/symbol-list)
https://api.iov-mainnet-ibc.iov.one/swagger/#/Query/Starname

**Comment by Kwonhyukjoon** [comment]
Thank you for your kind feedback. 
In order to resolve the issue, please send an email to support@cosmostation.io. Our CS team will help you to resolve the issue.
In the email, please elaborate more on the issues so that our CS team is able to resolve your issue as soon as possible. 

Thank you again for the feedback and I hope you have a great day.

**Comment by wannabit-yongjoo** [comment]
@Kwonhyukjoon  
Please try to find reappearance this error in Android side

**Comment by xpt1x** [comment]
@wannabit-yongjoo @Kwonhyukjoon 
I think i got it, why its happening

Its when, suppose i am on OSMO chain and want to send OSMO coin to a starname, i enter the starname and after resolving that starname, if that starname's OSMO resource contains sender's address himself, then it shows "Valid starname, but not matching address with this chain" where it should actually be the condition of "**Valid starname, but can not send to your own address**"

**Comment by Kwonhyukjoon** [comment]
Thank you! I'll fix it

**Comment by wannabit-yongjoo** [comment]
https://github.com/cosmostation/cosmostation-android/commit/8d9d8ece146f6c216a2e1bc8fa19bdbca669272f
