### ISSUE TITLE
Obsolete regex being used for starname service

### ISSUE THREAD

**Issue by xpt1x** [cosmostation/cosmostation-android#89]
Regex for checking a valid account name, valid domain name has been updated by Starname
Current one can be viewed here: [Starname Params](https://api-private-iov-mainnet-ibc.iov.one/starname/v1beta1/configuration/params)

Please update: 
https://github.com/cosmostation/cosmostation-android/blob/98f85879c033188ceae8951591efef042e4771e7/app/src/main/java/wannabit/io/cosmostaion/utils/WUtil.java#L2451-L2482

This is causing some new names to fail at starname resolution step at Send or related interfaces
Manually updating the regex will fix this in my opinion, but a better solution would be to get this from the api itself, as its kinda core to cosmostation

**Comment by Kwonhyukjoon** [comment]
Thank you!
I'll fix it

**Comment by wannabit-yongjoo** [comment]
https://github.com/cosmostation/cosmostation-ios/commit/5c1f3dc6419c7ddcf19cb034132659ed7c21218b

check ios and adjust it plz

**Comment by Kwonhyukjoon** [comment]
[2dab74a](https://github.com/cosmostation/cosmostation-android/commit/2dab74a40acbf9431a87fc9cf2f5889f28877ffc)
